language: node_js

os:
  - linux

node_js:
  - "--lts" # use latest stable node version

branches:
  only:
    - master

before_script:
  # for karma tests, start xvfb and give it some time to start
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

install:
  - npm install
  - npx lerna clean -y
  - npx lerna link
  - npx lerna bootstrap --no-ci

script:
    set -evx;
    npx lerna run --stream build-dist;
    npx lerna run --stream build-all;
    npx lerna run --stream lint;
    npm run build-esdoc;
    npx lerna run --stream test;
    npx lerna run --stream test-ts-definitions;
    npx lerna run --stream test-coverage;
    npx lerna run --stream test-browser -- -- --browsers PhantomJS --browserNoActivityTimeout 20000;
    npx lerna run --stream test-saucelabs;

after_success:
    npm run build-test-coverage-report;
    cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js;

addons:
  sauce_connect: true

notifications:
  slack:
    rooms:
      - js-joda:WtVY1EJYfAiiDW3QMnAWJZe2#travis
